### ISSUE TITLE
Datatrans has new Sandbox URLs

### ISSUE THREAD

**Issue by featuremedia** [simplificator/datatrans#13]
**Sandbox/Test Service URLs**

Payment pages: https://pay.sandbox.datatrans.com 
For example: https://pay.sandbox.datatrans.com/upp/jsp/upStart.jsp

Server to server APIs: https://api.sandbox.datatrans.com
For example: https://api.sandbox.datatrans.com/upp/jsp/XML_authorize.jsp

**Comment by schmijos** [comment]
The old pilot URLs don't work since 1st of February. The old production URLs will not work starting at March 1st.

You have to reconfigure like here:
https://github.com/renuo/datatrans/commit/e97d28af9353f47168b91f59ec04e0709378dbc0#diff-a8197eb60252ac655fb38c02629de3bf3aa9501af1a760e0106285dafa50e05c

**Comment by crackofdusk** [comment]
We are working on releasing a new gem version with the updated endpoints.

**Comment by crackofdusk** [comment]
Fixed by https://github.com/simplificator/datatrans/pull/32

**Comment by andyundso** [comment]
We just released [4.0.0](https://rubygems.org/gems/datatrans/versions/4.0.0). It contains the updated URLs.
